### ISSUE TITLE
Add New Encryption Method: Camelia

### ISSUE THREAD

**Issue by fncolon** [fncolon/encryptlab#23]
According to wikipedia: In cryptography, Camellia is a symmetric key block cipher with a block size of 128 bits and key sizes of 128, 192 and 256 bits. It was jointly developed by Mitsubishi Electric and NTT of Japan. The cipher has been approved for use by the ISO/IEC, the European Union's NESSIE project and the Japanese CRYPTREC project. The cipher has security levels and processing abilities comparable to the Advanced Encryption Standard.

**Usage**
The cipher was designed to be suitable for both software and hardware implementations, from low-cost smart cards to high-speed network systems. It is part of the Transport Layer Security (TLS) cryptographic protocol designed to provide communications security over a computer network such as the Internet.

**Note**: Although Camellia is patented, it is available under a royalty-free license

---

Block length = 128 bits
Key length = 128, 192 or 256 bits

---

## Block Diagram of Camellia Encryption for 128-bit Key
![Capture](https://user-images.githubusercontent.com/50759463/126483111-5092641d-e89e-484c-bfc1-00c667efff91.PNG)

## Block Diagram of Camellia Encryption for 192 or 256-bit Key
![Capture2](https://user-images.githubusercontent.com/50759463/126483132-3890e853-80ee-4f77-b414-0e3a19941c50.PNG)

## Block Diagram of Camellia Decryption for 128-bit Key
![Capture](https://user-images.githubusercontent.com/50759463/126483229-7f1f88d6-358c-497c-90d1-686e96f83e2f.PNG)

## Block Diagram of Camellia Decryption for 192 or 256-bit Key
![Capture](https://user-images.githubusercontent.com/50759463/126483245-ff1e5e5d-849c-4093-82ed-7a28688c6172.PNG)

**Comment by trasherdk** [comment]
Maybe adding a note: [Although **Camellia is patented**, it is available under a royalty-free license](https://en.wikipedia.org/wiki/Camellia_(cipher)#Patent_status)

**Comment by fncolon** [comment]
> Maybe adding a note: [Although **Camellia is patented**, it is available under a royalty-free license](https://en.wikipedia.org/wiki/Camellia_(cipher)#Patent_status)

Yes it's under the open source license, Nice idea, will add it thanks.

**Comment by fncolon** [comment]
@all-contributors please add @trasherdk for idea
