### ISSUE TITLE
.editorconfig

### ISSUE THREAD

**Issue by trasherdk** [fncolon/encryptlab#31]
Can I suggest adding a `.editorconfig` file helping IDE's not getting confused when code-style differs from their standard.

Something like:
```
root = true

[*]
indent_style = space
indent_size = 4
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true

[*.md]
trim_trailing_whitespace = false
```

**Comment by fncolon** [comment]
@trasherdk You can! but don't forget to make sure it's work by providing a video / link to see the video because i'm not using IDE

**Comment by trasherdk** [comment]
I'm not sure what you mean by `make sure it's work by providing a video / link` But here's a link to [EditorConfig](https://editorconfig.org/)

I noticed that indentation is not consistent between files. Some are `indent_size` 2 and some are 4.

Just out of curiosity. What are you using for code editor?

**Comment by fncolon** [comment]
> I'm not sure what you mean by `make sure it's work by providing a video / link` But here's a link to [EditorConfig](https://editorconfig.org/)
> 
> I noticed that indentation is not consistent between files. Some are `indent_size` 2 and some are 4.
> 
> Just out of curiosity. What are you using for code editor?

Do you mean to code? i'm using VSCode with prettier extension enabled, since i'm not using IDE to code, so i did not too care about indentation consistency.

**Comment by fncolon** [comment]
I mean make sure the editorcondig works by providing a video about the differences between using editorconfig and not.

**Comment by fncolon** [comment]
Since i will add #41, this issue will be closed, thanks for letting know about this.

**Comment by trasherdk** [comment]
Yes, good. I was moving to prettier too :smile:
