### ISSUE TITLE
Configure Eslint and Prettier with Pre Commit Hook

### ISSUE THREAD

**Issue by fncolon** [fncolon/encryptlab#41]
## Description

Configure Eslint and Prettier with Pre Commit Hook instead of using `.editorconfig` to fix and format files recursively.

## Tasks

- [ ] Configure eslint
- [ ] Configure prettier
- [ ] Add pre commit hook with husky

**Comment by trasherdk** [comment]
Do you want the PR for `prettier` I have prepared?

**Comment by fncolon** [comment]
> Do you want the PR for `prettier` I have prepared?
> 
> EDIT: https://github.com/trasherdk/encryptlab/tree/add/prettier

Sorry, but can you leave the task to me? look like you including `.editorconfig` and `prettier-eslint` is missing, i want to integrate eslint, prettier, husky together.

That's nice of you, thanks for the contributions.

**Comment by trasherdk** [comment]
No problem. I was not finished with the PR anyway :smiley:
